//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopalMarti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltOzellik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AltOzellik()
        {
            this.Urun_AltOzellik = new HashSet<Urun_AltOzellik>();
        }
    
        public int ID { get; set; }
        public string AltOzellikAdi { get; set; }
        public int OzellikID { get; set; }
        public string Aciklama { get; set; }
        public bool Silindi { get; set; }
    
        public virtual Ozellik Ozellik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urun_AltOzellik> Urun_AltOzellik { get; set; }
    }
}
