//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopalMarti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Firmalar()
        {
            this.Firma_Urunler = new HashSet<Firma_Urunler>();
        }
    
        public int ID { get; set; }
        public string FirmaAd { get; set; }
        public string KullaniciAd { get; set; }
        public string Sifre { get; set; }
        public string YetkiliAd { get; set; }
        public string YetkiliSoyad { get; set; }
        public string Telefon { get; set; }
        public string FirmaMail { get; set; }
        public string VergiNo { get; set; }
        public string VergiDairesi { get; set; }
        public bool OnayDurumu { get; set; }
        public bool Silindi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Firma_Urunler> Firma_Urunler { get; set; }
    }
}
