//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopalMarti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kampanyalar
    {
        public int ID { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public decimal KampanyaFiyati { get; set; }
        public int Stok { get; set; }
        public string Aciklama { get; set; }
        public int FirmaUrunID { get; set; }
        public bool Silindi { get; set; }
    }
}
