//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopalMarti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ozellik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ozellik()
        {
            this.AltOzellik = new HashSet<AltOzellik>();
            this.Urun_Ozellik = new HashSet<Urun_Ozellik>();
        }
    
        public int ID { get; set; }
        public string OzellikAdi { get; set; }
        public int KategoriID { get; set; }
        public int AltKategoriID { get; set; }
        public string Aciklama { get; set; }
        public bool Silindi { get; set; }
    
        public virtual AltKategoriler AltKategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AltOzellik> AltOzellik { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urun_Ozellik> Urun_Ozellik { get; set; }
    }
}
