//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopalMarti.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TopalMartiEntities2 : DbContext
    {
        public TopalMartiEntities2()
            : base("name=TopalMartiEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresler> Adresler { get; set; }
        public virtual DbSet<AltKategoriler> AltKategoriler { get; set; }
        public virtual DbSet<AltOzellik> AltOzellik { get; set; }
        public virtual DbSet<Firma_Urunler> Firma_Urunler { get; set; }
        public virtual DbSet<Firmalar> Firmalar { get; set; }
        public virtual DbSet<Kampanyalar> Kampanyalar { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Ozellik> Ozellik { get; set; }
        public virtual DbSet<SiparisDetaylari> SiparisDetaylari { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<Urun_AltOzellik> Urun_AltOzellik { get; set; }
        public virtual DbSet<Urun_Ozellik> Urun_Ozellik { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<UstKategoriler> UstKategoriler { get; set; }
        public virtual DbSet<Yorumlar> Yorumlar { get; set; }
    }
}
