//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopalMarti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun_Ozellik
    {
        public int ID { get; set; }
        public int UrunID { get; set; }
        public int OzellikID { get; set; }
        public bool Varmi { get; set; }
    
        public virtual Ozellik Ozellik { get; set; }
    }
}
