//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopalMarti.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Firma_Urunler = new HashSet<Firma_Urunler>();
        }
    
        public int UrunID { get; set; }
        public string UrunKodu { get; set; }
        public string UrunAd { get; set; }
        public int UrunUstKategoriNo { get; set; }
        public int UrunKategoriNo { get; set; }
        public int UrunAltKategoriNo { get; set; }
        public bool Silindi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Firma_Urunler> Firma_Urunler { get; set; }
        public virtual UstKategoriler UstKategoriler { get; set; }
    }
}
